// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TftComp struct {
	MatchID       string
	SummonerPuuid string
	CompData      []byte
}

type TftMatch struct {
	ID          string
	DataVersion string
	GameVersion string
	QueueID     int32
	GameType    string
	SetName     string
	SetNumber   int32
}

type TftSummoner struct {
	Puuid          string
	Name           pgtype.Text
	Tag            pgtype.Text
	SummonerID     pgtype.Text
	ProfileIconID  pgtype.Int4
	SummonerLevel  pgtype.Int4
	MatchesUpdated pgtype.Timestamp
}
