// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"TheCollectorDG/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type TftComp struct {
	MatchID       string
	SummonerPuuid string
	CompData      types.CompData
}

type TftMatch struct {
	ID          string
	DataVersion string
	GameVersion string
	QueueID     int32
	GameType    string
	SetName     string
	SetNumber   int32
}

type TftSummoner struct {
	Puuid                     string
	Name                      *string
	Tag                       *string
	SummonerID                *string
	ProfileIconID             *int32
	SummonerLevel             *int32
	FullUpdateTimestamp       pgtype.Timestamp
	BackgroundUpdateTimestamp pgtype.Timestamp
}
